"use client";

import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import type { Report } from "../types/report";

type Props = {
  report: Report;
};

type TailoredResult = {
  tailoredSummary: string;
  tailoredBullets: string[];
  tailoredSkills: string[];
  coverLetter: string;
};

export default function TailorResume({ report }: Props) {
  const [jobDescription, setJobDescription] = useState("");
  const [result, setResult] = useState<TailoredResult | null>(null);
  const [loading, setLoading] = useState(false);

  const tailoredScore = result
    ? Math.min(98, Math.max(88, report.atsScore + 12))
    : 0;

  useEffect(() => {
    function handleTailorJob(event: Event) {
      const customEvent = event as CustomEvent<string>;
      setJobDescription(customEvent.detail);
    }

    window.addEventListener("tailor-job", handleTailorJob);
    return () => window.removeEventListener("tailor-job", handleTailorJob);
  }, []);

  async function handleTailor() {
    if (!jobDescription.trim()) {
      alert("Paste a job description first.");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const response = await fetch("/api/tailor", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ report, jobDescription }),
      });

      const data = await response.json();

      if (!data.success) {
        alert(data.message || "Failed to tailor resume.");
        return;
      }

      setResult(data);
    } catch (error) {
      console.error(error);
      alert("Something went wrong while tailoring the resume.");
    } finally {
      setLoading(false);
    }
  }

  function addWrappedText(
    doc: jsPDF,
    text: string,
    x: number,
    y: number,
    maxWidth: number,
    lineHeight: number
  ) {
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return y + lines.length * lineHeight;
  }

  function downloadTailoredResume() {
    if (!result) return;

    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 18;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("TAILORED ATS RESUME", pageWidth / 2, y, { align: "center" });

    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Generated by Resume Roast", pageWidth / 2, y, {
      align: "center",
    });

    y += 12;
    doc.setDrawColor(249, 115, 22);
    doc.line(margin, y, pageWidth - margin, y);

    y += 12;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("PROFESSIONAL SUMMARY", margin, y);

    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y = addWrappedText(doc, result.tailoredSummary, margin, y, maxWidth, 5);

    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("PROFESSIONAL EXPERIENCE HIGHLIGHTS", margin, y);

    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    result.tailoredBullets.forEach((bullet) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      y = addWrappedText(doc, `• ${bullet}`, margin, y, maxWidth, 5) + 2;
    });

    y += 6;
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("CORE SKILLS", margin, y);

    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y = addWrappedText(
      doc,
      result.tailoredSkills.join(" • "),
      margin,
      y,
      maxWidth,
      5
    );

    y += 12;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(
      "Generated by Resume Roast. Review and personalize before submitting.",
      margin,
      y
    );

    doc.save("Tailored_ATS_Resume.pdf");
  }

  function downloadCoverLetter() {
    if (!result?.coverLetter) return;

    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 18;
    const maxWidth = pageWidth - margin * 2;
    let y = 22;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("COVER LETTER", pageWidth / 2, y, { align: "center" });

    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Generated by Resume Roast", pageWidth / 2, y, {
      align: "center",
    });

    y += 14;
    doc.setDrawColor(249, 115, 22);
    doc.line(margin, y, pageWidth - margin, y);

    y += 12;
    doc.setFontSize(11);
    doc.setTextColor(17, 24, 39);

    const paragraphs = result.coverLetter.split("\n").filter(Boolean);

    paragraphs.forEach((paragraph) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      y = addWrappedText(doc, paragraph, margin, y, maxWidth, 6) + 5;
    });

    doc.save("Tailored_Cover_Letter.pdf");
  }

  return (
    <div
      id="tailor-resume-section"
      className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-8 shadow-xl"
    >
      <h2 className="text-2xl font-extrabold text-orange-400">
        🎯 Tailor Resume for a Job
      </h2>

      <p className="mt-2 text-sm text-gray-400">
        Paste a job description or click Tailor Resume on a job card. Resume
        Roast will rewrite your resume for that exact role.
      </p>

      <textarea
        value={jobDescription}
        onChange={(e) => setJobDescription(e.target.value)}
        placeholder="Paste the job description here..."
        className="mt-5 min-h-44 w-full rounded-2xl border border-zinc-700 bg-black p-4 text-white outline-none focus:border-orange-500"
      />

      <button
        onClick={handleTailor}
        disabled={loading}
        className="mt-5 rounded-xl bg-orange-500 px-6 py-3 font-bold text-black transition hover:bg-orange-400 disabled:opacity-60"
      >
        {loading ? "Tailoring Resume..." : "Tailor Resume"}
      </button>

      {result && (
        <div className="mt-8 rounded-3xl border border-zinc-700 bg-black p-6">
          <div className="grid gap-5 md:grid-cols-3">
            <div className="rounded-2xl border border-green-500/30 bg-green-500/10 p-5 text-center">
              <p className="text-sm font-bold text-gray-400">ATS Match</p>
              <p className="mt-2 text-5xl font-extrabold text-green-400">
                {tailoredScore}%
              </p>
            </div>

            <div className="rounded-2xl border border-orange-500/30 bg-orange-500/10 p-5 text-center">
              <p className="text-sm font-bold text-gray-400">Keywords Added</p>
              <p className="mt-2 text-5xl font-extrabold text-orange-400">
                {result.tailoredSkills.length}
              </p>
            </div>

            <div className="rounded-2xl border border-zinc-700 bg-zinc-950 p-5">
              <p className="font-bold text-white">Ready to Apply</p>
              <ul className="mt-3 space-y-2 text-sm text-green-400">
                <li>✓ Summary rewritten</li>
                <li>✓ Bullets tailored</li>
                <li>✓ Skills optimized</li>
              </ul>
            </div>
          </div>

          <h3 className="mt-8 text-2xl font-extrabold text-green-400">
            AI Optimized Resume
          </h3>

          <h4 className="mt-5 font-bold text-orange-400">
            Professional Summary
          </h4>
          <p className="mt-2 leading-7 text-gray-300">
            {result.tailoredSummary}
          </p>

          <h4 className="mt-5 font-bold text-orange-400">
            Tailored Resume Bullets
          </h4>
          <ul className="mt-2 list-disc space-y-2 pl-5 text-gray-300">
            {result.tailoredBullets.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          <h4 className="mt-5 font-bold text-orange-400">Optimized Skills</h4>
          <div className="mt-2 flex flex-wrap gap-2">
            {result.tailoredSkills.map((skill) => (
              <span
                key={skill}
                className="rounded-full bg-orange-500/10 px-3 py-1 text-sm font-bold text-orange-300"
              >
                {skill}
              </span>
            ))}
          </div>

          {result.coverLetter && (
            <>
              <h4 className="mt-6 font-bold text-orange-400">Cover Letter</h4>
              <p className="mt-2 whitespace-pre-line leading-7 text-gray-300">
                {result.coverLetter}
              </p>
            </>
          )}

          <div className="mt-6 flex flex-wrap gap-3">
            <button
              onClick={downloadTailoredResume}
              className="rounded-xl bg-green-500 px-6 py-3 font-bold text-black transition hover:bg-green-400"
            >
              Download ATS Resume (PDF)
            </button>

            {result.coverLetter && (
              <button
                onClick={downloadCoverLetter}
                className="rounded-xl border border-zinc-700 px-6 py-3 font-bold text-white transition hover:bg-zinc-800"
              >
                Download Cover Letter (PDF)
              </button>
            )}

            <button
              onClick={() =>
                alert("Coming soon: interview questions for this job.")
              }
              className="rounded-xl border border-zinc-700 px-6 py-3 font-bold text-white transition hover:bg-zinc-800"
            >
              Interview Prep Soon
            </button>
          </div>
        </div>
      )}
    </div>
  );
}