"use client";

import { useState, type ReactNode } from "react";
import JobMatches from "../components/JobMatches";
import TailorResume from "../components/TailorResume";
import type { Report } from "../types/report";
import {
  CircularProgressbar,
  buildStyles,
} from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

export default function Home() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [status, setStatus] = useState("");
  const [report, setReport] = useState<Report | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  async function handleAnalyze() {
    if (!selectedFile) {
      setStatus("Please upload a resume first.");
      return;
    }

    try {
      setIsLoading(true);
      setStatus("AI recruiter is sharpening the red pen...");
      setReport(null);

      const formData = new FormData();
      formData.append("resume", selectedFile);

      const response = await fetch("/api/analyze", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        setStatus(data.message || "AI analysis failed.");
        return;
      }

      setReport({
        success: true,
        message: data.message || "Resume analyzed successfully!",
        fileName: data.fileName || selectedFile.name,
        atsScore: Number(data.atsScore) || 0,
        recruiterScore: Number(data.recruiterScore) || 0,
        hiringProbability: data.hiringProbability || "Medium",
        roast: data.roast || "No recruiter roast generated.",
        strengths: Array.isArray(data.strengths) ? data.strengths : [],
        weaknesses: Array.isArray(data.weaknesses) ? data.weaknesses : [],
        missingKeywords: Array.isArray(data.missingKeywords)
          ? data.missingKeywords
          : [],
        improvedSummary:
          data.improvedSummary || "No improved summary generated.",
        rewrittenBullets: Array.isArray(data.rewrittenBullets)
          ? data.rewrittenBullets
          : [],
        optimizedSkills: Array.isArray(data.optimizedSkills)
          ? data.optimizedSkills
          : [],
        interviewQuestions: Array.isArray(data.interviewQuestions)
          ? data.interviewQuestions
          : [],
        jobMatches: Array.isArray(data.jobMatches) ? data.jobMatches : [],
      });

      setStatus("Resume roasted successfully!");
    } catch (error) {
      console.error(error);
      setStatus("Something went wrong. The recruiter stormed out.");
    } finally {
      setIsLoading(false);
    }
  }

  async function copyText(text: string) {
    await navigator.clipboard.writeText(text);
    alert("Copied!");
  }

  function downloadImprovedResume() {
    if (!report) return;

    const resumeHtml = `
      <html>
        <head>
          <meta charset="utf-8" />
          <title>Improved Resume</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              color: #111827;
              line-height: 1.6;
              max-width: 800px;
              margin: 40px auto;
              padding: 20px;
            }
            h1 {
              font-size: 28px;
              margin-bottom: 6px;
              color: #111827;
            }
            h2 {
              font-size: 18px;
              border-bottom: 2px solid #f97316;
              padding-bottom: 6px;
              margin-top: 28px;
              color: #111827;
            }
            ul {
              padding-left: 22px;
            }
            li {
              margin-bottom: 8px;
            }
            .tag {
              display: inline-block;
              background: #fff7ed;
              color: #9a3412;
              padding: 6px 10px;
              margin: 4px;
              border-radius: 8px;
              font-size: 13px;
              font-weight: bold;
            }
            .footer {
              margin-top: 40px;
              font-size: 12px;
              color: #6b7280;
            }
          </style>
        </head>
        <body>
          <h1>ATS-Optimized Resume</h1>
          <p><strong>Generated by Resume Roast AI</strong></p>

          <h2>Professional Summary</h2>
          <p>${report.improvedSummary}</p>

          <h2>Optimized Resume Bullets</h2>
          <ul>
            ${report.rewrittenBullets
              .map((bullet) => `<li>${bullet}</li>`)
              .join("")}
          </ul>

          <h2>Optimized Skills</h2>
          <p>
            ${report.optimizedSkills
              .map((skill) => `<span class="tag">${skill}</span>`)
              .join("")}
          </p>

          <h2>Recommended ATS Keywords</h2>
          <p>
            ${report.missingKeywords
              .map((keyword) => `<span class="tag">${keyword}</span>`)
              .join("")}
          </p>

          <div class="footer">
            This resume draft was generated by Resume Roast AI. Please review before submitting.
          </div>
        </body>
      </html>
    `;

    const blob = new Blob([resumeHtml], {
      type: "application/msword",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    const cleanName =
      report.fileName?.replace(/\.[^/.]+$/, "") || "Improved_Resume";

    link.href = url;
    link.download = `${cleanName}_ATS_Optimized_Resume.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  function copyFullReport() {
    if (!report) return;

    const fullReport = `
Resume Roast Report

ATS Score: ${report.atsScore}/100
Recruiter Score: ${report.recruiterScore}/100
Hiring Probability: ${report.hiringProbability}

Recruiter Roast:
${report.roast}

Strengths:
${report.strengths.map((item) => `- ${item}`).join("\n")}

Weaknesses:
${report.weaknesses.map((item) => `- ${item}`).join("\n")}

Missing Keywords:
${report.missingKeywords.map((item) => `- ${item}`).join("\n")}

Improved Summary:
${report.improvedSummary}

Rewritten Resume Bullets:
${report.rewrittenBullets.map((item) => `- ${item}`).join("\n")}

Optimized Skills:
${report.optimizedSkills.map((item) => `- ${item}`).join("\n")}

Interview Questions:
${report.interviewQuestions.map((item) => `- ${item}`).join("\n")}

Best Job Matches:
${report.jobMatches
  .map(
    (job) =>
      `- ${job.company} | ${job.role} | ${job.location} | ${job.match}% match | ${job.url}`
  )
  .join("\n")}
`;

    copyText(fullReport);
  }

  return (
    <main className="min-h-screen bg-black px-5 py-8 text-white">
      <section className="mx-auto max-w-7xl text-center">
        <div className="mx-auto max-w-5xl">
          <p className="text-sm font-bold uppercase tracking-[0.35em] text-orange-500">
            Resume Roast AI
          </p>

          <h1 className="mt-6 text-5xl font-extrabold leading-tight md:text-7xl">
            Get Hired Faster.
            <br />
            Let AI Roast Your Resume.
          </h1>

          <p className="mx-auto mt-7 max-w-3xl text-lg text-gray-400 md:text-xl">
            ATS analysis, recruiter feedback, resume rewrite, missing keywords,
            and job matches — with just enough roast to hurt your ego and help
            your career.
          </p>

          <div className="mt-10 flex flex-wrap justify-center gap-4">
            <label className="cursor-pointer rounded-2xl bg-orange-500 px-9 py-4 text-lg font-extrabold text-black shadow-lg shadow-orange-500/20 transition hover:-translate-y-0.5 hover:bg-orange-400">
              Scan My Resume
              <input
                type="file"
                accept=".pdf,.doc,.docx"
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) {
                    setSelectedFile(file);
                    setStatus("");
                    setReport(null);
                  }
                }}
              />
            </label>

            <button className="rounded-2xl border border-zinc-700 px-9 py-4 font-bold transition hover:bg-white hover:text-black">
              Watch Demo
            </button>
          </div>
        </div>

        {selectedFile && (
          <div className="mx-auto mt-10 max-w-2xl rounded-3xl border border-zinc-800 bg-zinc-950 p-7 shadow-2xl">
            <p className="text-green-400">✅ Resume uploaded successfully</p>
            <p className="mt-3 text-lg font-bold">{selectedFile.name}</p>

            <button
              onClick={handleAnalyze}
              disabled={isLoading}
              className="mt-6 rounded-xl bg-white px-8 py-3 font-extrabold text-black transition hover:bg-zinc-200 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isLoading ? "Roasting..." : "Analyze Resume"}
            </button>

            {status && (
              <p className="mt-4 text-sm font-semibold text-orange-400">
                {status}
              </p>
            )}

            {isLoading && (
              <div className="mx-auto mt-5 h-8 w-8 animate-spin rounded-full border-4 border-zinc-700 border-t-orange-500" />
            )}
          </div>
        )}

        {report && (
          <div className="mt-8 flex flex-wrap justify-center gap-4">
            <button
              onClick={downloadImprovedResume}
              className="rounded-xl bg-green-500 px-7 py-3 font-bold text-black transition hover:bg-green-400"
            >
              Download Improved Resume
            </button>

            <button
              onClick={copyFullReport}
              className="rounded-xl bg-orange-500 px-7 py-3 font-bold text-black transition hover:bg-orange-400"
            >
              Copy Full Report
            </button>

            <button
              onClick={() =>
                alert("PDF export is coming next. Word download works now.")
              }
              className="rounded-xl border border-zinc-700 px-7 py-3 font-bold text-white transition hover:bg-zinc-900"
            >
              Download PDF Soon
            </button>
          </div>
        )}

        {report && <ReportSection report={report} copyText={copyText} />}
      </section>
    </main>
  );
}

function ReportSection({
  report,
  copyText,
}: {
  report: Report;
  copyText: (text: string) => void;
}) {
  return (
    <div className="mx-auto mt-8 max-w-7xl rounded-[2rem] border border-zinc-800 bg-zinc-950 p-6 text-left shadow-2xl md:p-10">
      <div className="text-center">
        <p className="text-sm uppercase tracking-[0.35em] text-gray-500">
          AI Recruiter Verdict
        </p>

        <h2 className="mt-3 text-4xl font-extrabold text-orange-500 md:text-6xl">
          Resume Roast Report
        </h2>

        {report.fileName && (
          <p className="mt-3 text-sm text-gray-500">{report.fileName}</p>
        )}
      </div>

      <div className="mt-10 grid gap-8 md:grid-cols-3">
        <GaugeCard title="ATS Score" value={report.atsScore} />
        <GaugeCard title="Recruiter Score" value={report.recruiterScore} />
        <ProbabilityCard value={report.hiringProbability} />
      </div>

      <RoastCard report={report} />

      <div className="grid gap-8 md:grid-cols-2">
        <ListCard title="✅ Strengths" items={report.strengths} />
        <ListCard title="❌ Weaknesses" items={report.weaknesses} />
      </div>

      <ListCard title="🔑 Missing Keywords" items={report.missingKeywords} />

      <CopyCard
        title="✍️ Improved Professional Summary"
        text={report.improvedSummary}
        copyText={copyText}
      />

      <CopyListCard
        title="🚀 Rewritten Resume Bullets"
        items={report.rewrittenBullets}
        copyText={copyText}
      />

      <CopyListCard
        title="🛠 Optimized Skills"
        items={report.optimizedSkills}
        copyText={copyText}
      />

      <ListCard
        title="🎯 Interview Questions"
        items={report.interviewQuestions}
      />

      <JobMatches jobs={report.jobMatches || []} />
      <TailorResume report={report} />

      <div className="mt-10 rounded-2xl border border-zinc-800 bg-black p-6 text-center">
        <p className="text-sm font-bold uppercase tracking-widest text-gray-500">
          ResumeRoast AI Preview Report
        </p>
        <p className="mt-2 text-gray-400">
          Built to roast weak resumes, rescue strong careers, and mildly offend
          bullet points.
        </p>
      </div>
    </div>
  );
}

function RoastCard({ report }: { report: Report }) {
  const roastTitle =
    report.atsScore >= 80
      ? "☕ Coffee Break Feedback"
      : report.atsScore >= 60
      ? "🔥 Recruiter Roast"
      : "🚨 ATS Crime Report";

  const funnyVerdict =
    report.atsScore >= 80
      ? "This resume is interview-ready, but a few bullets are still wearing casual slippers to a formal meeting."
      : report.atsScore >= 60
      ? "Your resume has good experience, but it is making recruiters dig like they are searching for treasure."
      : "This resume is not hopeless. But right now, ATS systems are looking at it like it joined the wrong meeting.";

  return (
    <div className="mt-8 rounded-3xl border border-orange-500/20 bg-gradient-to-br from-zinc-900 to-black p-8">
      <h3 className="text-2xl font-extrabold text-orange-400">{roastTitle}</h3>
      <p className="mt-5 rounded-2xl border border-zinc-800 bg-black p-5 text-lg leading-8 text-gray-200">
        {funnyVerdict}
      </p>
      <p className="mt-5 leading-8 text-gray-300">{report.roast}</p>
    </div>
  );
}

function GaugeCard({ title, value }: { title: string; value: number }) {
  const score = Math.max(0, Math.min(100, value));
  const pathColor =
    score >= 75 ? "#22c55e" : score >= 50 ? "#f97316" : "#ef4444";

  return (
    <div className="rounded-3xl border border-zinc-800 bg-zinc-900 p-8 text-center shadow-xl">
      <div className="mx-auto h-44 w-44">
        <CircularProgressbar
          value={score}
          text={`${score}`}
          styles={buildStyles({
            textColor: pathColor,
            pathColor,
            trailColor: "#27272a",
            textSize: "22px",
          })}
        />
      </div>
      <p className="mt-5 text-lg font-bold text-gray-300">{title}</p>
    </div>
  );
}

function ProbabilityCard({ value }: { value: string }) {
  const color = value.toLowerCase().includes("high")
    ? "text-green-400"
    : value.toLowerCase().includes("low")
    ? "text-red-400"
    : "text-orange-400";

  return (
    <div className="rounded-3xl border border-zinc-800 bg-zinc-900 p-8 text-center shadow-xl">
      <p className="text-lg font-bold text-gray-400">Hiring Probability</p>
      <p className={`mt-10 text-6xl font-extrabold ${color}`}>{value}</p>
    </div>
  );
}

function ListCard({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-8 shadow-xl">
      <h3 className="text-2xl font-extrabold text-orange-400">{title}</h3>
      <ul className="mt-5 list-disc space-y-3 pl-5 text-gray-300">
        {items.length > 0 ? (
          items.map((item) => <li key={item}>{item}</li>)
        ) : (
          <li>No data available.</li>
        )}
      </ul>
    </div>
  );
}

function CopyCard({
  title,
  text,
  copyText,
}: {
  title: string;
  text: string;
  copyText: (text: string) => void;
}) {
  return (
    <div className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-8 shadow-xl">
      <h3 className="text-2xl font-extrabold text-orange-400">{title}</h3>
      <button
        onClick={() => copyText(text)}
        className="mt-4 rounded-xl border border-zinc-700 px-5 py-2 text-sm font-bold text-white transition hover:bg-zinc-800"
      >
        Copy
      </button>
      <p className="mt-5 leading-8 text-gray-300">{text}</p>
    </div>
  );
}

function CopyListCard({
  title,
  items,
  copyText,
}: {
  title: string;
  items: string[];
  copyText: (text: string) => void;
}) {
  const combined = items.map((item) => `• ${item}`).join("\n");

  return (
    <div className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-8 shadow-xl">
      <h3 className="text-2xl font-extrabold text-orange-400">{title}</h3>
      <button
        onClick={() => copyText(combined)}
        className="mt-4 rounded-xl border border-zinc-700 px-5 py-2 text-sm font-bold text-white transition hover:bg-zinc-800"
      >
        Copy
      </button>

      <ul className="mt-5 list-disc space-y-3 pl-5 text-gray-300">
        {items.length > 0 ? (
          items.map((item) => <li key={item}>{item}</li>)
        ) : (
          <li>No data available.</li>
        )}
      </ul>
    </div>
  );
}