import jsPDF from "jspdf";

type PdfResumeData = {
  tailoredSummary?: string;
  tailoredBullets?: string[];
  tailoredSkills?: string[];
  atsScore?: number;
  recruiterScore?: number;
  hiringProbability?: string;
  roast?: string;
  strengths?: string[];
  weaknesses?: string[];
  missingKeywords?: string[];
  improvedSummary?: string;
  optimizedSkills?: string[];
  interviewQuestions?: string[];
  jobMatches?: any[];
};

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
) {
  const lines = doc.splitTextToSize(text || "", maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function checkPage(doc: jsPDF, y: number) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y > pageHeight - 25) {
    doc.addPage();
    return 20;
  }
  return y;
}

function sectionTitle(doc: jsPDF, title: string, y: number, margin: number) {
  y = checkPage(doc, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(249, 115, 22);
  doc.text(title, margin, y);
  return y + 7;
}

function listSection(
  doc: jsPDF,
  title: string,
  items: string[] | undefined,
  y: number,
  margin: number,
  maxWidth: number
) {
  if (!items || items.length === 0) return y;

  y = sectionTitle(doc, title, y, margin);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(31, 41, 55);

  items.forEach((item) => {
    y = checkPage(doc, y);
    y = addWrappedText(doc, `• ${item}`, margin, y, maxWidth, 5) + 2;
  });

  return y + 5;
}

export function downloadResumePdf(data: PdfResumeData) {
  const doc = new jsPDF("p", "mm", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const maxWidth = pageWidth - margin * 2;
  let y = 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(249, 115, 22);
  doc.text("RESUME ROAST REPORT", pageWidth / 2, y, { align: "center" });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text("Generated by Resume Roast AI", pageWidth / 2, y, { align: "center" });

  y += 12;
  doc.setDrawColor(249, 115, 22);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);

  y += 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39);
  doc.text(`ATS Score: ${data.atsScore ?? "N/A"}`, margin, y);
  doc.text(`Recruiter Score: ${data.recruiterScore ?? "N/A"}`, margin + 60, y);
  doc.text(`Hiring: ${data.hiringProbability ?? "N/A"}`, margin + 125, y);

  y += 14;

  if (data.roast) {
    y = sectionTitle(doc, "RECRUITER ROAST", y, margin);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);
    y = addWrappedText(doc, data.roast, margin, y, maxWidth, 5) + 8;
  }

  y = listSection(doc, "STRENGTHS", data.strengths, y, margin, maxWidth);
  y = listSection(doc, "WEAKNESSES", data.weaknesses, y, margin, maxWidth);
  y = listSection(doc, "MISSING KEYWORDS", data.missingKeywords, y, margin, maxWidth);

  if (data.improvedSummary || data.tailoredSummary) {
    y = sectionTitle(doc, "IMPROVED SUMMARY", y, margin);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);
    y = addWrappedText(
      doc,
      data.improvedSummary || data.tailoredSummary || "",
      margin,
      y,
      maxWidth,
      5
    ) + 8;
  }

  y = listSection(
    doc,
    "OPTIMIZED SKILLS",
    data.optimizedSkills || data.tailoredSkills,
    y,
    margin,
    maxWidth
  );

  y = listSection(
    doc,
    "REWRITTEN BULLETS",
    data.tailoredBullets,
    y,
    margin,
    maxWidth
  );

  y = listSection(
    doc,
    "INTERVIEW QUESTIONS",
    data.interviewQuestions,
    y,
    margin,
    maxWidth
  );

  if (data.jobMatches && data.jobMatches.length > 0) {
    y = sectionTitle(doc, "JOB MATCHES", y, margin);

    data.jobMatches.forEach((job) => {
      y = checkPage(doc, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);

      const jobText = `${job.company || "Company"} - ${job.role || "Role"} - ${
        job.match || "N/A"
      }% match`;

      y = addWrappedText(doc, `• ${jobText}`, margin, y, maxWidth, 5) + 2;
    });

    y += 5;
  }

  y = checkPage(doc, y + 8);
  doc.setDrawColor(229, 231, 235);
  doc.line(margin, y, pageWidth - margin, y);

  y += 7;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(
    "Generated by Resume Roast AI. Review and personalize before submitting.",
    margin,
    y
  );

  doc.save("Resume_Roast_Report.pdf");
}