import jsPDF from "jspdf";

type PdfResumeData = {
  tailoredSummary: string;
  tailoredBullets: string[];
  tailoredSkills: string[];
};

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
) {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

export function downloadResumePdf(data: PdfResumeData) {
  const doc = new jsPDF("p", "mm", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const maxWidth = pageWidth - margin * 2;

  let y = 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("PROFESSIONAL RESUME", pageWidth / 2, y, { align: "center" });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Generated by Resume Roast", pageWidth / 2, y, { align: "center" });

  y += 10;
  doc.setDrawColor(249, 115, 22);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);

  y += 12;
  doc.setTextColor(17, 24, 39);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("PROFESSIONAL SUMMARY", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = addWrappedText(doc, data.tailoredSummary, margin, y, maxWidth, 5);

  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("PROFESSIONAL EXPERIENCE", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  data.tailoredBullets.forEach((bullet) => {
    if (y > pageHeight - 30) {
      doc.addPage();
      y = 20;
    }

    y = addWrappedText(doc, `• ${bullet}`, margin, y, maxWidth, 5) + 2;
  });

  y += 6;

  if (y > pageHeight - 40) {
    doc.addPage();
    y = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("CORE SKILLS", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = addWrappedText(
    doc,
    data.tailoredSkills.join(" • "),
    margin,
    y,
    maxWidth,
    5
  );

  y += 12;
  doc.setDrawColor(229, 231, 235);
  doc.line(margin, y, pageWidth - margin, y);

  y += 7;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(
    "Generated by Resume Roast. Review and personalize before submitting.",
    margin,
    y
  );

  doc.save("Resume_Roast_ATS_Resume.pdf");
}